name: LiteStar Code Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run LiteStar Scanner on this repo
      run: python main.py .

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: litestar-analysis-report
        path: litestar_analysis_report.md
